import type { AppLanguage } from '../../api';

export const progressCopy = {
  en: {
    progress: 'Your Journey',
    subtitle: 'A quieter mind grows one return at a time.',
    journeyHub: 'Journey sections',
    journeyTab: 'Journey',
    gardenTab: 'Garden',
    gardenHubSubtitle: 'Your personal calm world, grown through genuine practice.',
    currentRhythm: 'Current Rhythm',
    dayStreak: 'Day streak',
    longestRhythm: 'Longest rhythm',
    activeThisWeek: 'This week',
    activeDays: 'active days',
    freeze: 'Freeze',
    nextMilestone: 'Next',
    oneMoreDay: 'One more quiet return reaches your {target}-day rhythm.',
    moreDays: '{count} more quiet returns reach your {target}-day rhythm.',
    moreDaysFew: '{count} more quiet returns reach your {target}-day rhythm.',
    moreDaysMany: '{count} more quiet returns reach your {target}-day rhythm.',
    reflection: 'Luna’s Reflection',
    thisWeek: 'This Week with Luna',
    listeningMinutes: 'Listening minutes',
    completedPractices: 'Completed practices',
    practiceDays: 'Practice days',
    comparedMore: '+{count} min compared with last week',
    comparedLess: '{count} min less than last week',
    comparedSame: 'The same listening time as last week',
    noComparison: 'A previous active week will unlock a meaningful comparison.',
    weeklyActivity: 'Daily listening activity',
    minutesUnit: 'minutes',
    noWeeklyActivity: 'Your week is still open. One quiet minute is enough to begin.',
    moodJourney: 'Mood Journey',
    moodSubtitle: 'Seven local days, exactly as you recorded them.',
    calmSignal: 'Calm signal',
    stressSignal: 'Stress signal',
    sleepQuality: 'Sleep quality',
    noMoodHistory: 'Empty days stay empty. A few more check-ins will make the journey visible.',
    noCheckin: 'No check-in',
    today: 'Today',
    mood: 'Mood',
    sleep: 'Sleep',
    practice: 'Practice',
    listening: 'Listening',
    noPractice: 'No completed practice',
    close: 'Close',
    personalPatterns: 'Personal Patterns',
    patternsSubtitle: 'Only patterns supported by your completed practice history.',
    patternsForming: 'Luna is still learning your rhythm. Complete a few more practices to reveal meaningful patterns.',
    monthlyRhythm: '30-day rhythm',
    averagePractice: 'Average practice',
    favoriteTime: 'Preferred time',
    moonGarden: 'Moon Garden',
    gardenLevel: 'Level',
    availableSeeds: 'Available Moon Seeds',
    plantedUpgrades: 'Planted upgrades',
    nextGardenUpgrade: 'Next garden upgrade',
    gardenComplete: 'Your Full Moon Garden is flourishing.',
    enterGarden: 'Enter Garden',
    achievements: 'Achievements',
    unlockedCount: '{unlocked} / {total} unlocked',
    latestAchievements: 'Your latest quiet milestones.',
    noAchievements: 'Your first achievement will appear after a completed practice.',
    viewAllAchievements: 'View all achievements',
    allAchievements: 'All Achievements',
    all: 'All',
    unlocked: 'Unlocked',
    inProgress: 'In progress',
    locked: 'Locked',
    practiceCategory: 'Practice',
    rhythmCategory: 'Rhythm',
    wellnessCategory: 'Wellness',
    gardenCategory: 'Garden',
    premiumCategory: 'Premium',
    earned: 'Earned {date}',
    achievementProgress: '{current} of {target}',
    nextStep: 'Next Gentle Step',
    startPractice: 'Start practice',
    premium: 'Premium',
    included: 'Included',
    recommendationUnavailable: 'Luna is refreshing the published practice catalog. You can explore Library in the meantime.',
    openLibrary: 'Open Library',
    diagnostics: 'Journey diagnostics',
    diagnosticCurrentWeek: 'Current local week',
    diagnosticPreviousWeek: 'Previous local week',
    diagnosticSessions: 'Source playback sessions',
    diagnosticSeconds: 'Verified listening seconds',
    diagnosticDates: 'Active local dates',
    diagnosticStreak: 'Current / longest streak',
    diagnosticMoods: 'Mood entries',
    diagnosticGarden: 'Garden upgrades',
    diagnosticAchievements: 'Unlocked achievements',
    diagnosticRefresh: 'Last refresh',
    hide: 'Hide',
    show: 'Show',
    min: 'min'
  },
  ru: {
    progress: 'Ваш путь',
    subtitle: 'Спокойствие растёт с каждым мягким возвращением.',
    journeyHub: 'Разделы пути',
    journeyTab: 'Путь',
    gardenTab: 'Сад',
    gardenHubSubtitle: 'Твоё личное пространство спокойствия, которое растёт вместе с практикой.',
    currentRhythm: 'Текущий ритм',
    dayStreak: 'Дней подряд',
    longestRhythm: 'Самый долгий ритм',
    activeThisWeek: 'На этой неделе',
    activeDays: 'дней практики',
    freeze: 'Заморозка',
    nextMilestone: 'Дальше',
    oneMoreDay: 'Ещё одно тихое возвращение создаст ритм в {target} дней.',
    moreDays: 'Ещё {count} тихих возвращения — и ритм достигнет {target} дней.',
    moreDaysFew: 'Ещё {count} тихих возвращения — и ритм достигнет {target} дней.',
    moreDaysMany: 'Ещё {count} тихих возвращений — и ритм достигнет {target} дней.',
    reflection: 'Наблюдение Луны',
    thisWeek: 'Эта неделя с Луной',
    listeningMinutes: 'Минуты практики',
    completedPractices: 'Завершённые практики',
    practiceDays: 'Дни практики',
    comparedMore: '+{count} мин по сравнению с прошлой неделей',
    comparedLess: 'На {count} мин меньше, чем на прошлой неделе',
    comparedSame: 'Столько же минут, сколько на прошлой неделе',
    noComparison: 'Сравнение появится после ещё одной недели с практикой.',
    weeklyActivity: 'Практика по дням',
    minutesUnit: 'минуты',
    noWeeklyActivity: 'Эта неделя ещё открыта. Для начала достаточно одной тихой минуты.',
    moodJourney: 'Путь настроения',
    moodSubtitle: 'Семь локальных дней — только отмеченные тобой состояния.',
    calmSignal: 'Уровень спокойствия',
    stressSignal: 'Уровень напряжения',
    sleepQuality: 'Качество сна',
    noMoodHistory: 'Пустые дни остаются пустыми. Несколько чек-инов помогут увидеть путь.',
    noCheckin: 'Нет чек-ина',
    today: 'Сегодня',
    mood: 'Настроение',
    sleep: 'Сон',
    practice: 'Практика',
    listening: 'Практика',
    noPractice: 'Нет завершённой практики',
    close: 'Закрыть',
    personalPatterns: 'Личные закономерности',
    patternsSubtitle: 'Только наблюдения, подтверждённые историей завершённых практик.',
    patternsForming: 'Луна пока изучает ваш ритм. Завершите ещё несколько практик, чтобы появились достоверные закономерности.',
    monthlyRhythm: 'Ритм за 30 дней',
    averagePractice: 'Средняя практика',
    favoriteTime: 'Привычное время',
    moonGarden: 'Лунный сад',
    gardenLevel: 'Уровень',
    availableSeeds: 'Доступные лунные семена',
    plantedUpgrades: 'Посажено улучшений',
    nextGardenUpgrade: 'Следующее улучшение сада',
    gardenComplete: 'Твой Сад полной луны расцветает.',
    enterGarden: 'Открыть сад',
    achievements: 'Достижения',
    unlockedCount: 'Открыто {unlocked} из {total}',
    latestAchievements: 'Твои последние тихие вехи.',
    noAchievements: 'Первое достижение появится после завершённой практики.',
    viewAllAchievements: 'Посмотреть все достижения',
    allAchievements: 'Все достижения',
    all: 'Все',
    unlocked: 'Открыто',
    inProgress: 'В процессе',
    locked: 'Закрыто',
    practiceCategory: 'Практика',
    rhythmCategory: 'Ритм',
    wellnessCategory: 'Самочувствие',
    gardenCategory: 'Сад',
    premiumCategory: 'Premium',
    earned: 'Открыто {date}',
    achievementProgress: '{current} из {target}',
    nextStep: 'Следующий мягкий шаг',
    startPractice: 'Начать практику',
    premium: 'Premium',
    included: 'Доступно',
    recommendationUnavailable: 'Луна обновляет каталог опубликованных практик. Пока можно открыть Библиотеку.',
    openLibrary: 'Открыть Библиотеку',
    diagnostics: 'Диагностика пути',
    diagnosticCurrentWeek: 'Текущая локальная неделя',
    diagnosticPreviousWeek: 'Предыдущая локальная неделя',
    diagnosticSessions: 'Исходные сессии воспроизведения',
    diagnosticSeconds: 'Подтверждённые секунды практики',
    diagnosticDates: 'Локальные даты активности',
    diagnosticStreak: 'Текущий / самый долгий ритм',
    diagnosticMoods: 'Записи настроения',
    diagnosticGarden: 'Улучшения сада',
    diagnosticAchievements: 'Открытые достижения',
    diagnosticRefresh: 'Последнее обновление',
    hide: 'Скрыть',
    show: 'Показать',
    min: 'мин'
  }
} as const satisfies Record<AppLanguage, Record<string, string>>;

export function progressText(language: AppLanguage, key: keyof typeof progressCopy.en, replacements: Record<string, string | number> = {}) {
  let value: string = progressCopy[language][key];
  Object.entries(replacements).forEach(([name, replacement]) => {
    value = value.replace(`{${name}}`, String(replacement));
  });
  return value;
}
